apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-liqui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings-liqui
  template:
    metadata:
      labels:
        app: greetings-liqui
    spec:
      containers:
        - name: app
          image: moldovean/greetings-liquibase:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          imagePullPolicy: Always